// Code generated by mockery v2.52.3. DO NOT EDIT.

package ratelim

import mock "github.com/stretchr/testify/mock"

// MockHash64 is an autogenerated mock type for the Hash64 type
type MockHash64 struct {
	mock.Mock
}

type MockHash64_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHash64) EXPECT() *MockHash64_Expecter {
	return &MockHash64_Expecter{mock: &_m.Mock}
}

// Sum64 provides a mock function with no fields
func (_m *MockHash64) Sum64() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sum64")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockHash64_Sum64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sum64'
type MockHash64_Sum64_Call struct {
	*mock.Call
}

// Sum64 is a helper method to define mock.On call
func (_e *MockHash64_Expecter) Sum64() *MockHash64_Sum64_Call {
	return &MockHash64_Sum64_Call{Call: _e.mock.On("Sum64")}
}

func (_c *MockHash64_Sum64_Call) Run(run func()) *MockHash64_Sum64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHash64_Sum64_Call) Return(_a0 uint64) *MockHash64_Sum64_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHash64_Sum64_Call) RunAndReturn(run func() uint64) *MockHash64_Sum64_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *MockHash64) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHash64_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockHash64_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockHash64_Expecter) Write(p interface{}) *MockHash64_Write_Call {
	return &MockHash64_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockHash64_Write_Call) Run(run func(p []byte)) *MockHash64_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockHash64_Write_Call) Return(n int, err error) *MockHash64_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHash64_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockHash64_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHash64 creates a new instance of MockHash64. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHash64(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHash64 {
	mock := &MockHash64{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
