run:
  timeout: 5m
  tests: true
  concurrency: 4

issues:
  # Exclude directories that are not part of your source code.
  exclude-dirs:
    - vendor
  # Exclude files such as generated files.
  exclude-files:
    - ".*_generated.go"
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  enable-all: true
  disable:
    - tenv      # deprecated (since v1.64.0) due to: replaced by usetesting.
    - depguard  # Have issues with go.work style
    - godox     # will have a lot of todo

linters-settings:
  govet:
    # Enable shadow checking (replacing the deprecated check-shadowing).
    shadow: true
  cyclop:
    skip-tests: true
    max-complexity: 9
  varnamelen:
    ignore-names:
      - tt
    ignore-decls:
      - wg sync.WaitGroup
      - r *http.Request
      - w http.ResponseWriter