with-expecter: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/Sengoku11/go-monorepo/pkg/logger:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/alerter:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/middleware:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/fflag:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/errcode:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/environment:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/bootstrap:
    config:
      all: true
  github.com/Sengoku11/go-monorepo/pkg/ratelim:
    config:
      all: true
