// Code generated by mockery v2.52.3. DO NOT EDIT.

package fflag

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	openfeature "github.com/open-feature/go-sdk/openfeature"
)

// MockMockClient is an autogenerated mock type for the MockClient type
type MockMockClient struct {
	mock.Mock
}

type MockMockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMockClient) EXPECT() *MockMockClient_Expecter {
	return &MockMockClient_Expecter{mock: &_m.Mock}
}

// AddHandler provides a mock function with given fields: eventType, callback
func (_m *MockMockClient) AddHandler(eventType openfeature.EventType, callback openfeature.EventCallback) {
	_m.Called(eventType, callback)
}

// MockMockClient_AddHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHandler'
type MockMockClient_AddHandler_Call struct {
	*mock.Call
}

// AddHandler is a helper method to define mock.On call
//   - eventType openfeature.EventType
//   - callback openfeature.EventCallback
func (_e *MockMockClient_Expecter) AddHandler(eventType interface{}, callback interface{}) *MockMockClient_AddHandler_Call {
	return &MockMockClient_AddHandler_Call{Call: _e.mock.On("AddHandler", eventType, callback)}
}

func (_c *MockMockClient_AddHandler_Call) Run(run func(eventType openfeature.EventType, callback openfeature.EventCallback)) *MockMockClient_AddHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(openfeature.EventType), args[1].(openfeature.EventCallback))
	})
	return _c
}

func (_c *MockMockClient_AddHandler_Call) Return() *MockMockClient_AddHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMockClient_AddHandler_Call) RunAndReturn(run func(openfeature.EventType, openfeature.EventCallback)) *MockMockClient_AddHandler_Call {
	_c.Run(run)
	return _c
}

// AddHooks provides a mock function with given fields: hooks
func (_m *MockMockClient) AddHooks(hooks ...openfeature.Hook) {
	_va := make([]interface{}, len(hooks))
	for _i := range hooks {
		_va[_i] = hooks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockMockClient_AddHooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHooks'
type MockMockClient_AddHooks_Call struct {
	*mock.Call
}

// AddHooks is a helper method to define mock.On call
//   - hooks ...openfeature.Hook
func (_e *MockMockClient_Expecter) AddHooks(hooks ...interface{}) *MockMockClient_AddHooks_Call {
	return &MockMockClient_AddHooks_Call{Call: _e.mock.On("AddHooks",
		append([]interface{}{}, hooks...)...)}
}

func (_c *MockMockClient_AddHooks_Call) Run(run func(hooks ...openfeature.Hook)) *MockMockClient_AddHooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Hook, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Hook)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_AddHooks_Call) Return() *MockMockClient_AddHooks_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMockClient_AddHooks_Call) RunAndReturn(run func(...openfeature.Hook)) *MockMockClient_AddHooks_Call {
	_c.Run(run)
	return _c
}

// Boolean provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) Boolean(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) bool {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Boolean")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) bool); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockMockClient_Boolean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boolean'
type MockMockClient_Boolean_Call struct {
	*mock.Call
}

// Boolean is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue bool
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) Boolean(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_Boolean_Call {
	return &MockMockClient_Boolean_Call{Call: _e.mock.On("Boolean",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_Boolean_Call) Run(run func(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_Boolean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_Boolean_Call) Return(_a0 bool) *MockMockClient_Boolean_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_Boolean_Call) RunAndReturn(run func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) bool) *MockMockClient_Boolean_Call {
	_c.Call.Return(run)
	return _c
}

// BooleanValue provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) BooleanValue(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (bool, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BooleanValue")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) (bool, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) bool); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_BooleanValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BooleanValue'
type MockMockClient_BooleanValue_Call struct {
	*mock.Call
}

// BooleanValue is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue bool
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) BooleanValue(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_BooleanValue_Call {
	return &MockMockClient_BooleanValue_Call{Call: _e.mock.On("BooleanValue",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_BooleanValue_Call) Run(run func(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_BooleanValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_BooleanValue_Call) Return(_a0 bool, _a1 error) *MockMockClient_BooleanValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_BooleanValue_Call) RunAndReturn(run func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) (bool, error)) *MockMockClient_BooleanValue_Call {
	_c.Call.Return(run)
	return _c
}

// BooleanValueDetails provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) BooleanValueDetails(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (openfeature.BooleanEvaluationDetails, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BooleanValueDetails")
	}

	var r0 openfeature.BooleanEvaluationDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.BooleanEvaluationDetails, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) openfeature.BooleanEvaluationDetails); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(openfeature.BooleanEvaluationDetails)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_BooleanValueDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BooleanValueDetails'
type MockMockClient_BooleanValueDetails_Call struct {
	*mock.Call
}

// BooleanValueDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue bool
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) BooleanValueDetails(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_BooleanValueDetails_Call {
	return &MockMockClient_BooleanValueDetails_Call{Call: _e.mock.On("BooleanValueDetails",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_BooleanValueDetails_Call) Run(run func(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_BooleanValueDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_BooleanValueDetails_Call) Return(_a0 openfeature.BooleanEvaluationDetails, _a1 error) *MockMockClient_BooleanValueDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_BooleanValueDetails_Call) RunAndReturn(run func(context.Context, string, bool, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.BooleanEvaluationDetails, error)) *MockMockClient_BooleanValueDetails_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluationContext provides a mock function with no fields
func (_m *MockMockClient) EvaluationContext() openfeature.EvaluationContext {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EvaluationContext")
	}

	var r0 openfeature.EvaluationContext
	if rf, ok := ret.Get(0).(func() openfeature.EvaluationContext); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(openfeature.EvaluationContext)
	}

	return r0
}

// MockMockClient_EvaluationContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluationContext'
type MockMockClient_EvaluationContext_Call struct {
	*mock.Call
}

// EvaluationContext is a helper method to define mock.On call
func (_e *MockMockClient_Expecter) EvaluationContext() *MockMockClient_EvaluationContext_Call {
	return &MockMockClient_EvaluationContext_Call{Call: _e.mock.On("EvaluationContext")}
}

func (_c *MockMockClient_EvaluationContext_Call) Run(run func()) *MockMockClient_EvaluationContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockClient_EvaluationContext_Call) Return(_a0 openfeature.EvaluationContext) *MockMockClient_EvaluationContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_EvaluationContext_Call) RunAndReturn(run func() openfeature.EvaluationContext) *MockMockClient_EvaluationContext_Call {
	_c.Call.Return(run)
	return _c
}

// Float provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) Float(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) float64 {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Float")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) float64); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockMockClient_Float_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Float'
type MockMockClient_Float_Call struct {
	*mock.Call
}

// Float is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue float64
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) Float(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_Float_Call {
	return &MockMockClient_Float_Call{Call: _e.mock.On("Float",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_Float_Call) Run(run func(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_Float_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_Float_Call) Return(_a0 float64) *MockMockClient_Float_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_Float_Call) RunAndReturn(run func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) float64) *MockMockClient_Float_Call {
	_c.Call.Return(run)
	return _c
}

// FloatValue provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) FloatValue(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (float64, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FloatValue")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) (float64, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) float64); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_FloatValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FloatValue'
type MockMockClient_FloatValue_Call struct {
	*mock.Call
}

// FloatValue is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue float64
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) FloatValue(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_FloatValue_Call {
	return &MockMockClient_FloatValue_Call{Call: _e.mock.On("FloatValue",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_FloatValue_Call) Run(run func(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_FloatValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_FloatValue_Call) Return(_a0 float64, _a1 error) *MockMockClient_FloatValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_FloatValue_Call) RunAndReturn(run func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) (float64, error)) *MockMockClient_FloatValue_Call {
	_c.Call.Return(run)
	return _c
}

// FloatValueDetails provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) FloatValueDetails(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (openfeature.FloatEvaluationDetails, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FloatValueDetails")
	}

	var r0 openfeature.FloatEvaluationDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.FloatEvaluationDetails, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) openfeature.FloatEvaluationDetails); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(openfeature.FloatEvaluationDetails)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_FloatValueDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FloatValueDetails'
type MockMockClient_FloatValueDetails_Call struct {
	*mock.Call
}

// FloatValueDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue float64
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) FloatValueDetails(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_FloatValueDetails_Call {
	return &MockMockClient_FloatValueDetails_Call{Call: _e.mock.On("FloatValueDetails",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_FloatValueDetails_Call) Run(run func(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_FloatValueDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_FloatValueDetails_Call) Return(_a0 openfeature.FloatEvaluationDetails, _a1 error) *MockMockClient_FloatValueDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_FloatValueDetails_Call) RunAndReturn(run func(context.Context, string, float64, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.FloatEvaluationDetails, error)) *MockMockClient_FloatValueDetails_Call {
	_c.Call.Return(run)
	return _c
}

// Int provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) Int(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) int64 {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Int")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) int64); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockMockClient_Int_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Int'
type MockMockClient_Int_Call struct {
	*mock.Call
}

// Int is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue int64
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) Int(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_Int_Call {
	return &MockMockClient_Int_Call{Call: _e.mock.On("Int",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_Int_Call) Run(run func(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_Int_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_Int_Call) Return(_a0 int64) *MockMockClient_Int_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_Int_Call) RunAndReturn(run func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) int64) *MockMockClient_Int_Call {
	_c.Call.Return(run)
	return _c
}

// IntValue provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) IntValue(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (int64, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for IntValue")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) (int64, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) int64); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_IntValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntValue'
type MockMockClient_IntValue_Call struct {
	*mock.Call
}

// IntValue is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue int64
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) IntValue(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_IntValue_Call {
	return &MockMockClient_IntValue_Call{Call: _e.mock.On("IntValue",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_IntValue_Call) Run(run func(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_IntValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_IntValue_Call) Return(_a0 int64, _a1 error) *MockMockClient_IntValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_IntValue_Call) RunAndReturn(run func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) (int64, error)) *MockMockClient_IntValue_Call {
	_c.Call.Return(run)
	return _c
}

// IntValueDetails provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) IntValueDetails(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (openfeature.IntEvaluationDetails, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for IntValueDetails")
	}

	var r0 openfeature.IntEvaluationDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.IntEvaluationDetails, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) openfeature.IntEvaluationDetails); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(openfeature.IntEvaluationDetails)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_IntValueDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntValueDetails'
type MockMockClient_IntValueDetails_Call struct {
	*mock.Call
}

// IntValueDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue int64
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) IntValueDetails(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_IntValueDetails_Call {
	return &MockMockClient_IntValueDetails_Call{Call: _e.mock.On("IntValueDetails",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_IntValueDetails_Call) Run(run func(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_IntValueDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_IntValueDetails_Call) Return(_a0 openfeature.IntEvaluationDetails, _a1 error) *MockMockClient_IntValueDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_IntValueDetails_Call) RunAndReturn(run func(context.Context, string, int64, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.IntEvaluationDetails, error)) *MockMockClient_IntValueDetails_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockMockClient) Metadata() openfeature.ClientMetadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 openfeature.ClientMetadata
	if rf, ok := ret.Get(0).(func() openfeature.ClientMetadata); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(openfeature.ClientMetadata)
	}

	return r0
}

// MockMockClient_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockMockClient_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockMockClient_Expecter) Metadata() *MockMockClient_Metadata_Call {
	return &MockMockClient_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockMockClient_Metadata_Call) Run(run func()) *MockMockClient_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockClient_Metadata_Call) Return(_a0 openfeature.ClientMetadata) *MockMockClient_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_Metadata_Call) RunAndReturn(run func() openfeature.ClientMetadata) *MockMockClient_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Object provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) Object(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) interface{} {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Object")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) interface{}); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockMockClient_Object_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Object'
type MockMockClient_Object_Call struct {
	*mock.Call
}

// Object is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue interface{}
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) Object(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_Object_Call {
	return &MockMockClient_Object_Call{Call: _e.mock.On("Object",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_Object_Call) Run(run func(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_Object_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_Object_Call) Return(_a0 interface{}) *MockMockClient_Object_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_Object_Call) RunAndReturn(run func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) interface{}) *MockMockClient_Object_Call {
	_c.Call.Return(run)
	return _c
}

// ObjectValue provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) ObjectValue(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (interface{}, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ObjectValue")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) (interface{}, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) interface{}); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_ObjectValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObjectValue'
type MockMockClient_ObjectValue_Call struct {
	*mock.Call
}

// ObjectValue is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue interface{}
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) ObjectValue(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_ObjectValue_Call {
	return &MockMockClient_ObjectValue_Call{Call: _e.mock.On("ObjectValue",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_ObjectValue_Call) Run(run func(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_ObjectValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_ObjectValue_Call) Return(_a0 interface{}, _a1 error) *MockMockClient_ObjectValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_ObjectValue_Call) RunAndReturn(run func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) (interface{}, error)) *MockMockClient_ObjectValue_Call {
	_c.Call.Return(run)
	return _c
}

// ObjectValueDetails provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) ObjectValueDetails(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (openfeature.InterfaceEvaluationDetails, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ObjectValueDetails")
	}

	var r0 openfeature.InterfaceEvaluationDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.InterfaceEvaluationDetails, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) openfeature.InterfaceEvaluationDetails); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(openfeature.InterfaceEvaluationDetails)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_ObjectValueDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObjectValueDetails'
type MockMockClient_ObjectValueDetails_Call struct {
	*mock.Call
}

// ObjectValueDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue interface{}
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) ObjectValueDetails(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_ObjectValueDetails_Call {
	return &MockMockClient_ObjectValueDetails_Call{Call: _e.mock.On("ObjectValueDetails",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_ObjectValueDetails_Call) Run(run func(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_ObjectValueDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_ObjectValueDetails_Call) Return(_a0 openfeature.InterfaceEvaluationDetails, _a1 error) *MockMockClient_ObjectValueDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_ObjectValueDetails_Call) RunAndReturn(run func(context.Context, string, interface{}, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.InterfaceEvaluationDetails, error)) *MockMockClient_ObjectValueDetails_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHandler provides a mock function with given fields: eventType, callback
func (_m *MockMockClient) RemoveHandler(eventType openfeature.EventType, callback openfeature.EventCallback) {
	_m.Called(eventType, callback)
}

// MockMockClient_RemoveHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHandler'
type MockMockClient_RemoveHandler_Call struct {
	*mock.Call
}

// RemoveHandler is a helper method to define mock.On call
//   - eventType openfeature.EventType
//   - callback openfeature.EventCallback
func (_e *MockMockClient_Expecter) RemoveHandler(eventType interface{}, callback interface{}) *MockMockClient_RemoveHandler_Call {
	return &MockMockClient_RemoveHandler_Call{Call: _e.mock.On("RemoveHandler", eventType, callback)}
}

func (_c *MockMockClient_RemoveHandler_Call) Run(run func(eventType openfeature.EventType, callback openfeature.EventCallback)) *MockMockClient_RemoveHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(openfeature.EventType), args[1].(openfeature.EventCallback))
	})
	return _c
}

func (_c *MockMockClient_RemoveHandler_Call) Return() *MockMockClient_RemoveHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMockClient_RemoveHandler_Call) RunAndReturn(run func(openfeature.EventType, openfeature.EventCallback)) *MockMockClient_RemoveHandler_Call {
	_c.Run(run)
	return _c
}

// SetEvaluationContext provides a mock function with given fields: evalCtx
func (_m *MockMockClient) SetEvaluationContext(evalCtx openfeature.EvaluationContext) {
	_m.Called(evalCtx)
}

// MockMockClient_SetEvaluationContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEvaluationContext'
type MockMockClient_SetEvaluationContext_Call struct {
	*mock.Call
}

// SetEvaluationContext is a helper method to define mock.On call
//   - evalCtx openfeature.EvaluationContext
func (_e *MockMockClient_Expecter) SetEvaluationContext(evalCtx interface{}) *MockMockClient_SetEvaluationContext_Call {
	return &MockMockClient_SetEvaluationContext_Call{Call: _e.mock.On("SetEvaluationContext", evalCtx)}
}

func (_c *MockMockClient_SetEvaluationContext_Call) Run(run func(evalCtx openfeature.EvaluationContext)) *MockMockClient_SetEvaluationContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(openfeature.EvaluationContext))
	})
	return _c
}

func (_c *MockMockClient_SetEvaluationContext_Call) Return() *MockMockClient_SetEvaluationContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMockClient_SetEvaluationContext_Call) RunAndReturn(run func(openfeature.EvaluationContext)) *MockMockClient_SetEvaluationContext_Call {
	_c.Run(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockMockClient) State() openfeature.State {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 openfeature.State
	if rf, ok := ret.Get(0).(func() openfeature.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(openfeature.State)
	}

	return r0
}

// MockMockClient_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockMockClient_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockMockClient_Expecter) State() *MockMockClient_State_Call {
	return &MockMockClient_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockMockClient_State_Call) Run(run func()) *MockMockClient_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockClient_State_Call) Return(_a0 openfeature.State) *MockMockClient_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_State_Call) RunAndReturn(run func() openfeature.State) *MockMockClient_State_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) String(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) string {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) string); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMockClient_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockMockClient_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue string
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) String(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_String_Call {
	return &MockMockClient_String_Call{Call: _e.mock.On("String",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_String_Call) Run(run func(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_String_Call) Return(_a0 string) *MockMockClient_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockClient_String_Call) RunAndReturn(run func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) string) *MockMockClient_String_Call {
	_c.Call.Return(run)
	return _c
}

// StringValue provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) StringValue(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StringValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) (string, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) string); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_StringValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringValue'
type MockMockClient_StringValue_Call struct {
	*mock.Call
}

// StringValue is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue string
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) StringValue(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_StringValue_Call {
	return &MockMockClient_StringValue_Call{Call: _e.mock.On("StringValue",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_StringValue_Call) Run(run func(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_StringValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_StringValue_Call) Return(_a0 string, _a1 error) *MockMockClient_StringValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_StringValue_Call) RunAndReturn(run func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) (string, error)) *MockMockClient_StringValue_Call {
	_c.Call.Return(run)
	return _c
}

// StringValueDetails provides a mock function with given fields: ctx, flag, defaultValue, evalCtx, options
func (_m *MockMockClient) StringValueDetails(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.EvaluationContext, options ...openfeature.Option) (openfeature.StringEvaluationDetails, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, flag, defaultValue, evalCtx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StringValueDetails")
	}

	var r0 openfeature.StringEvaluationDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.StringEvaluationDetails, error)); ok {
		return rf(ctx, flag, defaultValue, evalCtx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) openfeature.StringEvaluationDetails); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r0 = ret.Get(0).(openfeature.StringEvaluationDetails)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) error); ok {
		r1 = rf(ctx, flag, defaultValue, evalCtx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMockClient_StringValueDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringValueDetails'
type MockMockClient_StringValueDetails_Call struct {
	*mock.Call
}

// StringValueDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue string
//   - evalCtx openfeature.EvaluationContext
//   - options ...openfeature.Option
func (_e *MockMockClient_Expecter) StringValueDetails(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}, options ...interface{}) *MockMockClient_StringValueDetails_Call {
	return &MockMockClient_StringValueDetails_Call{Call: _e.mock.On("StringValueDetails",
		append([]interface{}{ctx, flag, defaultValue, evalCtx}, options...)...)}
}

func (_c *MockMockClient_StringValueDetails_Call) Run(run func(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.EvaluationContext, options ...openfeature.Option)) *MockMockClient_StringValueDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]openfeature.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(openfeature.Option)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(openfeature.EvaluationContext), variadicArgs...)
	})
	return _c
}

func (_c *MockMockClient_StringValueDetails_Call) Return(_a0 openfeature.StringEvaluationDetails, _a1 error) *MockMockClient_StringValueDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMockClient_StringValueDetails_Call) RunAndReturn(run func(context.Context, string, string, openfeature.EvaluationContext, ...openfeature.Option) (openfeature.StringEvaluationDetails, error)) *MockMockClient_StringValueDetails_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function with given fields: ctx, trackingEventName, evalCtx, details
func (_m *MockMockClient) Track(ctx context.Context, trackingEventName string, evalCtx openfeature.EvaluationContext, details openfeature.TrackingEventDetails) {
	_m.Called(ctx, trackingEventName, evalCtx, details)
}

// MockMockClient_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockMockClient_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingEventName string
//   - evalCtx openfeature.EvaluationContext
//   - details openfeature.TrackingEventDetails
func (_e *MockMockClient_Expecter) Track(ctx interface{}, trackingEventName interface{}, evalCtx interface{}, details interface{}) *MockMockClient_Track_Call {
	return &MockMockClient_Track_Call{Call: _e.mock.On("Track", ctx, trackingEventName, evalCtx, details)}
}

func (_c *MockMockClient_Track_Call) Run(run func(ctx context.Context, trackingEventName string, evalCtx openfeature.EvaluationContext, details openfeature.TrackingEventDetails)) *MockMockClient_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(openfeature.EvaluationContext), args[3].(openfeature.TrackingEventDetails))
	})
	return _c
}

func (_c *MockMockClient_Track_Call) Return() *MockMockClient_Track_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMockClient_Track_Call) RunAndReturn(run func(context.Context, string, openfeature.EvaluationContext, openfeature.TrackingEventDetails)) *MockMockClient_Track_Call {
	_c.Run(run)
	return _c
}

// NewMockMockClient creates a new instance of MockMockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMockClient {
	mock := &MockMockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
