// Code generated by mockery v2.52.3. DO NOT EDIT.

package fflag

import mock "github.com/stretchr/testify/mock"

// MockBoolCallback is an autogenerated mock type for the BoolCallback type
type MockBoolCallback struct {
	mock.Mock
}

type MockBoolCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoolCallback) EXPECT() *MockBoolCallback_Expecter {
	return &MockBoolCallback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockBoolCallback) Execute(_a0 bool, _a1 error) {
	_m.Called(_a0, _a1)
}

// MockBoolCallback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockBoolCallback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 bool
//   - _a1 error
func (_e *MockBoolCallback_Expecter) Execute(_a0 interface{}, _a1 interface{}) *MockBoolCallback_Execute_Call {
	return &MockBoolCallback_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *MockBoolCallback_Execute_Call) Run(run func(_a0 bool, _a1 error)) *MockBoolCallback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(error))
	})
	return _c
}

func (_c *MockBoolCallback_Execute_Call) Return() *MockBoolCallback_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBoolCallback_Execute_Call) RunAndReturn(run func(bool, error)) *MockBoolCallback_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockBoolCallback creates a new instance of MockBoolCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoolCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoolCallback {
	mock := &MockBoolCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
