// Code generated by mockery v2.52.3. DO NOT EDIT.

package fflag

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	openfeature "github.com/open-feature/go-sdk/openfeature"
)

// MockMockProvider is an autogenerated mock type for the MockProvider type
type MockMockProvider struct {
	mock.Mock
}

type MockMockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMockProvider) EXPECT() *MockMockProvider_Expecter {
	return &MockMockProvider_Expecter{mock: &_m.Mock}
}

// BooleanEvaluation provides a mock function with given fields: ctx, flag, defaultValue, evalCtx
func (_m *MockMockProvider) BooleanEvaluation(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.FlattenedContext) openfeature.BoolResolutionDetail {
	ret := _m.Called(ctx, flag, defaultValue, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for BooleanEvaluation")
	}

	var r0 openfeature.BoolResolutionDetail
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, openfeature.FlattenedContext) openfeature.BoolResolutionDetail); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx)
	} else {
		r0 = ret.Get(0).(openfeature.BoolResolutionDetail)
	}

	return r0
}

// MockMockProvider_BooleanEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BooleanEvaluation'
type MockMockProvider_BooleanEvaluation_Call struct {
	*mock.Call
}

// BooleanEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue bool
//   - evalCtx openfeature.FlattenedContext
func (_e *MockMockProvider_Expecter) BooleanEvaluation(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}) *MockMockProvider_BooleanEvaluation_Call {
	return &MockMockProvider_BooleanEvaluation_Call{Call: _e.mock.On("BooleanEvaluation", ctx, flag, defaultValue, evalCtx)}
}

func (_c *MockMockProvider_BooleanEvaluation_Call) Run(run func(ctx context.Context, flag string, defaultValue bool, evalCtx openfeature.FlattenedContext)) *MockMockProvider_BooleanEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(openfeature.FlattenedContext))
	})
	return _c
}

func (_c *MockMockProvider_BooleanEvaluation_Call) Return(_a0 openfeature.BoolResolutionDetail) *MockMockProvider_BooleanEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_BooleanEvaluation_Call) RunAndReturn(run func(context.Context, string, bool, openfeature.FlattenedContext) openfeature.BoolResolutionDetail) *MockMockProvider_BooleanEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// FloatEvaluation provides a mock function with given fields: ctx, flag, defaultValue, evalCtx
func (_m *MockMockProvider) FloatEvaluation(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.FlattenedContext) openfeature.FloatResolutionDetail {
	ret := _m.Called(ctx, flag, defaultValue, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for FloatEvaluation")
	}

	var r0 openfeature.FloatResolutionDetail
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, openfeature.FlattenedContext) openfeature.FloatResolutionDetail); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx)
	} else {
		r0 = ret.Get(0).(openfeature.FloatResolutionDetail)
	}

	return r0
}

// MockMockProvider_FloatEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FloatEvaluation'
type MockMockProvider_FloatEvaluation_Call struct {
	*mock.Call
}

// FloatEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue float64
//   - evalCtx openfeature.FlattenedContext
func (_e *MockMockProvider_Expecter) FloatEvaluation(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}) *MockMockProvider_FloatEvaluation_Call {
	return &MockMockProvider_FloatEvaluation_Call{Call: _e.mock.On("FloatEvaluation", ctx, flag, defaultValue, evalCtx)}
}

func (_c *MockMockProvider_FloatEvaluation_Call) Run(run func(ctx context.Context, flag string, defaultValue float64, evalCtx openfeature.FlattenedContext)) *MockMockProvider_FloatEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(openfeature.FlattenedContext))
	})
	return _c
}

func (_c *MockMockProvider_FloatEvaluation_Call) Return(_a0 openfeature.FloatResolutionDetail) *MockMockProvider_FloatEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_FloatEvaluation_Call) RunAndReturn(run func(context.Context, string, float64, openfeature.FlattenedContext) openfeature.FloatResolutionDetail) *MockMockProvider_FloatEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// Hooks provides a mock function with no fields
func (_m *MockMockProvider) Hooks() []openfeature.Hook {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hooks")
	}

	var r0 []openfeature.Hook
	if rf, ok := ret.Get(0).(func() []openfeature.Hook); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]openfeature.Hook)
		}
	}

	return r0
}

// MockMockProvider_Hooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hooks'
type MockMockProvider_Hooks_Call struct {
	*mock.Call
}

// Hooks is a helper method to define mock.On call
func (_e *MockMockProvider_Expecter) Hooks() *MockMockProvider_Hooks_Call {
	return &MockMockProvider_Hooks_Call{Call: _e.mock.On("Hooks")}
}

func (_c *MockMockProvider_Hooks_Call) Run(run func()) *MockMockProvider_Hooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockProvider_Hooks_Call) Return(_a0 []openfeature.Hook) *MockMockProvider_Hooks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_Hooks_Call) RunAndReturn(run func() []openfeature.Hook) *MockMockProvider_Hooks_Call {
	_c.Call.Return(run)
	return _c
}

// IntEvaluation provides a mock function with given fields: ctx, flag, defaultValue, evalCtx
func (_m *MockMockProvider) IntEvaluation(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.FlattenedContext) openfeature.IntResolutionDetail {
	ret := _m.Called(ctx, flag, defaultValue, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for IntEvaluation")
	}

	var r0 openfeature.IntResolutionDetail
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, openfeature.FlattenedContext) openfeature.IntResolutionDetail); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx)
	} else {
		r0 = ret.Get(0).(openfeature.IntResolutionDetail)
	}

	return r0
}

// MockMockProvider_IntEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntEvaluation'
type MockMockProvider_IntEvaluation_Call struct {
	*mock.Call
}

// IntEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue int64
//   - evalCtx openfeature.FlattenedContext
func (_e *MockMockProvider_Expecter) IntEvaluation(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}) *MockMockProvider_IntEvaluation_Call {
	return &MockMockProvider_IntEvaluation_Call{Call: _e.mock.On("IntEvaluation", ctx, flag, defaultValue, evalCtx)}
}

func (_c *MockMockProvider_IntEvaluation_Call) Run(run func(ctx context.Context, flag string, defaultValue int64, evalCtx openfeature.FlattenedContext)) *MockMockProvider_IntEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(openfeature.FlattenedContext))
	})
	return _c
}

func (_c *MockMockProvider_IntEvaluation_Call) Return(_a0 openfeature.IntResolutionDetail) *MockMockProvider_IntEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_IntEvaluation_Call) RunAndReturn(run func(context.Context, string, int64, openfeature.FlattenedContext) openfeature.IntResolutionDetail) *MockMockProvider_IntEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockMockProvider) Metadata() openfeature.Metadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 openfeature.Metadata
	if rf, ok := ret.Get(0).(func() openfeature.Metadata); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(openfeature.Metadata)
	}

	return r0
}

// MockMockProvider_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockMockProvider_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockMockProvider_Expecter) Metadata() *MockMockProvider_Metadata_Call {
	return &MockMockProvider_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockMockProvider_Metadata_Call) Run(run func()) *MockMockProvider_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockProvider_Metadata_Call) Return(_a0 openfeature.Metadata) *MockMockProvider_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_Metadata_Call) RunAndReturn(run func() openfeature.Metadata) *MockMockProvider_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// ObjectEvaluation provides a mock function with given fields: ctx, flag, defaultValue, evalCtx
func (_m *MockMockProvider) ObjectEvaluation(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.FlattenedContext) openfeature.InterfaceResolutionDetail {
	ret := _m.Called(ctx, flag, defaultValue, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for ObjectEvaluation")
	}

	var r0 openfeature.InterfaceResolutionDetail
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, openfeature.FlattenedContext) openfeature.InterfaceResolutionDetail); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx)
	} else {
		r0 = ret.Get(0).(openfeature.InterfaceResolutionDetail)
	}

	return r0
}

// MockMockProvider_ObjectEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObjectEvaluation'
type MockMockProvider_ObjectEvaluation_Call struct {
	*mock.Call
}

// ObjectEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue interface{}
//   - evalCtx openfeature.FlattenedContext
func (_e *MockMockProvider_Expecter) ObjectEvaluation(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}) *MockMockProvider_ObjectEvaluation_Call {
	return &MockMockProvider_ObjectEvaluation_Call{Call: _e.mock.On("ObjectEvaluation", ctx, flag, defaultValue, evalCtx)}
}

func (_c *MockMockProvider_ObjectEvaluation_Call) Run(run func(ctx context.Context, flag string, defaultValue interface{}, evalCtx openfeature.FlattenedContext)) *MockMockProvider_ObjectEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(openfeature.FlattenedContext))
	})
	return _c
}

func (_c *MockMockProvider_ObjectEvaluation_Call) Return(_a0 openfeature.InterfaceResolutionDetail) *MockMockProvider_ObjectEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_ObjectEvaluation_Call) RunAndReturn(run func(context.Context, string, interface{}, openfeature.FlattenedContext) openfeature.InterfaceResolutionDetail) *MockMockProvider_ObjectEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// StringEvaluation provides a mock function with given fields: ctx, flag, defaultValue, evalCtx
func (_m *MockMockProvider) StringEvaluation(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.FlattenedContext) openfeature.StringResolutionDetail {
	ret := _m.Called(ctx, flag, defaultValue, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for StringEvaluation")
	}

	var r0 openfeature.StringResolutionDetail
	if rf, ok := ret.Get(0).(func(context.Context, string, string, openfeature.FlattenedContext) openfeature.StringResolutionDetail); ok {
		r0 = rf(ctx, flag, defaultValue, evalCtx)
	} else {
		r0 = ret.Get(0).(openfeature.StringResolutionDetail)
	}

	return r0
}

// MockMockProvider_StringEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringEvaluation'
type MockMockProvider_StringEvaluation_Call struct {
	*mock.Call
}

// StringEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue string
//   - evalCtx openfeature.FlattenedContext
func (_e *MockMockProvider_Expecter) StringEvaluation(ctx interface{}, flag interface{}, defaultValue interface{}, evalCtx interface{}) *MockMockProvider_StringEvaluation_Call {
	return &MockMockProvider_StringEvaluation_Call{Call: _e.mock.On("StringEvaluation", ctx, flag, defaultValue, evalCtx)}
}

func (_c *MockMockProvider_StringEvaluation_Call) Run(run func(ctx context.Context, flag string, defaultValue string, evalCtx openfeature.FlattenedContext)) *MockMockProvider_StringEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(openfeature.FlattenedContext))
	})
	return _c
}

func (_c *MockMockProvider_StringEvaluation_Call) Return(_a0 openfeature.StringResolutionDetail) *MockMockProvider_StringEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMockProvider_StringEvaluation_Call) RunAndReturn(run func(context.Context, string, string, openfeature.FlattenedContext) openfeature.StringResolutionDetail) *MockMockProvider_StringEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMockProvider creates a new instance of MockMockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMockProvider {
	mock := &MockMockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
