// Code generated by mockery v2.52.3. DO NOT EDIT.

package alerter

import (
	context "context"

	alerter "github.com/Sengoku11/go-monorepo/pkg/alerter"

	mock "github.com/stretchr/testify/mock"
)

// MockAlerter is an autogenerated mock type for the Alerter type
type MockAlerter struct {
	mock.Mock
}

type MockAlerter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlerter) EXPECT() *MockAlerter_Expecter {
	return &MockAlerter_Expecter{mock: &_m.Mock}
}

// Alert provides a mock function with given fields: ctx, event
func (_m *MockAlerter) Alert(ctx context.Context, event alerter.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Alert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, alerter.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlerter_Alert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alert'
type MockAlerter_Alert_Call struct {
	*mock.Call
}

// Alert is a helper method to define mock.On call
//   - ctx context.Context
//   - event alerter.Event
func (_e *MockAlerter_Expecter) Alert(ctx interface{}, event interface{}) *MockAlerter_Alert_Call {
	return &MockAlerter_Alert_Call{Call: _e.mock.On("Alert", ctx, event)}
}

func (_c *MockAlerter_Alert_Call) Run(run func(ctx context.Context, event alerter.Event)) *MockAlerter_Alert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(alerter.Event))
	})
	return _c
}

func (_c *MockAlerter_Alert_Call) Return(_a0 error) *MockAlerter_Alert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlerter_Alert_Call) RunAndReturn(run func(context.Context, alerter.Event) error) *MockAlerter_Alert_Call {
	_c.Call.Return(run)
	return _c
}

// HandleError provides a mock function with given fields: err, event
func (_m *MockAlerter) HandleError(err error, event alerter.Event) {
	_m.Called(err, event)
}

// MockAlerter_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type MockAlerter_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - err error
//   - event alerter.Event
func (_e *MockAlerter_Expecter) HandleError(err interface{}, event interface{}) *MockAlerter_HandleError_Call {
	return &MockAlerter_HandleError_Call{Call: _e.mock.On("HandleError", err, event)}
}

func (_c *MockAlerter_HandleError_Call) Run(run func(err error, event alerter.Event)) *MockAlerter_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error), args[1].(alerter.Event))
	})
	return _c
}

func (_c *MockAlerter_HandleError_Call) Return() *MockAlerter_HandleError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAlerter_HandleError_Call) RunAndReturn(run func(error, alerter.Event)) *MockAlerter_HandleError_Call {
	_c.Run(run)
	return _c
}

// NewMockAlerter creates a new instance of MockAlerter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlerter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlerter {
	mock := &MockAlerter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
