// Code generated by mockery v2.52.3. DO NOT EDIT.

package alerter

import (
	alertchan "github.com/Sengoku11/go-monorepo/pkg/alerter/alertchan"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAlerter is an autogenerated mock type for the Alerter type
type MockAlerter struct {
	mock.Mock
}

type MockAlerter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlerter) EXPECT() *MockAlerter_Expecter {
	return &MockAlerter_Expecter{mock: &_m.Mock}
}

// Alert provides a mock function with given fields: ctx, channel, message, payload
func (_m *MockAlerter) Alert(ctx context.Context, channel alertchan.Channel, message string, payload map[string]any) error {
	ret := _m.Called(ctx, channel, message, payload)

	if len(ret) == 0 {
		panic("no return value specified for Alert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, alertchan.Channel, string, map[string]any) error); ok {
		r0 = rf(ctx, channel, message, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlerter_Alert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alert'
type MockAlerter_Alert_Call struct {
	*mock.Call
}

// Alert is a helper method to define mock.On call
//   - ctx context.Context
//   - channel alertchan.Channel
//   - message string
//   - payload map[string]any
func (_e *MockAlerter_Expecter) Alert(ctx interface{}, channel interface{}, message interface{}, payload interface{}) *MockAlerter_Alert_Call {
	return &MockAlerter_Alert_Call{Call: _e.mock.On("Alert", ctx, channel, message, payload)}
}

func (_c *MockAlerter_Alert_Call) Run(run func(ctx context.Context, channel alertchan.Channel, message string, payload map[string]any)) *MockAlerter_Alert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(alertchan.Channel), args[2].(string), args[3].(map[string]any))
	})
	return _c
}

func (_c *MockAlerter_Alert_Call) Return(_a0 error) *MockAlerter_Alert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlerter_Alert_Call) RunAndReturn(run func(context.Context, alertchan.Channel, string, map[string]any) error) *MockAlerter_Alert_Call {
	_c.Call.Return(run)
	return _c
}

// HandleError provides a mock function with given fields: err, message, payload
func (_m *MockAlerter) HandleError(err error, message string, payload map[string]any) {
	_m.Called(err, message, payload)
}

// MockAlerter_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type MockAlerter_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - err error
//   - message string
//   - payload map[string]any
func (_e *MockAlerter_Expecter) HandleError(err interface{}, message interface{}, payload interface{}) *MockAlerter_HandleError_Call {
	return &MockAlerter_HandleError_Call{Call: _e.mock.On("HandleError", err, message, payload)}
}

func (_c *MockAlerter_HandleError_Call) Run(run func(err error, message string, payload map[string]any)) *MockAlerter_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error), args[1].(string), args[2].(map[string]any))
	})
	return _c
}

func (_c *MockAlerter_HandleError_Call) Return() *MockAlerter_HandleError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAlerter_HandleError_Call) RunAndReturn(run func(error, string, map[string]any)) *MockAlerter_HandleError_Call {
	_c.Run(run)
	return _c
}

// NewMockAlerter creates a new instance of MockAlerter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlerter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlerter {
	mock := &MockAlerter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
