// Code generated by "stringer -type=Code -output=generated_errors_string.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUpstream-1000]
	_ = x[ErrUpstreamTimeout-1001]
	_ = x[ErrUpstreamInternal-1002]
	_ = x[ErrUpstreamNotFound-1003]
	_ = x[ErrUpstreamBadRequest-1004]
	_ = x[ErrUpstreamServiceUnavailable-1005]
	_ = x[ErrUpstreamRateLimited-1006]
	_ = x[ErrUpstreamConnectionRefused-1007]
	_ = x[ErrUpstreamMalformedResponse-1008]
	_ = x[ErrUpstreamAuthFailed-1009]
}

const _Code_name = "ErrUpstreamErrUpstreamTimeoutErrUpstreamInternalErrUpstreamNotFoundErrUpstreamBadRequestErrUpstreamServiceUnavailableErrUpstreamRateLimitedErrUpstreamConnectionRefusedErrUpstreamMalformedResponseErrUpstreamAuthFailed"

var _Code_index = [...]uint8{0, 11, 29, 48, 67, 88, 117, 139, 167, 195, 216}

func (i Code) String() string {
	i -= 1000
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
