// Code generated by generrors; DO NOT EDIT.
package errcode

// AllCodes is an auto-generated slice containing all error codes.
var AllCodes = []Code{
	ErrUpstreamInternal, // 1002
	ErrUpstreamNotFound, // 1003
	ErrUpstreamBadRequest, // 1004
	ErrUpstreamMalformedResponse, // 1008
	ErrUpstreamTimeout, // 1001
	ErrUpstreamServiceUnavailable, // 1005
	ErrUpstreamConnectionRefused, // 1007
	ErrUpstreamAuthFailed, // 1009
	ErrUpstream, // 1000
	ErrUpstreamRateLimited, // 1006
}
