// Code generated by generrors; DO NOT EDIT.
package errcode

var AllCodes = []Code{
	ErrUpstream, // 1000
	ErrUpstreamTimeout, // 1001
	ErrUpstreamInternal, // 1002
	ErrUpstreamNotFound, // 1003
	ErrUpstreamBadRequest, // 1004
	ErrUpstreamServiceUnavailable, // 1005
	ErrUpstreamRateLimited, // 1006
	ErrUpstreamConnectionRefused, // 1007
	ErrUpstreamMalformedResponse, // 1008
	ErrUpstreamAuthFailed, // 1009
}
