// cmd/generrors/gen.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	// Set the directory of the errcode package relative to this generator.
	// This generator assumes that the errcode package is located at pkg/errcode.
	dir := filepath.Join("..", "..", "pkg", "errcode")

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.AllErrors)
	if err != nil {
		log.Fatalf("failed to parse package: %v", err)
	}

	// Assume there's only one package in the directory.
	var pkg *ast.Package
	for _, p := range pkgs {
		pkg = p
		break
	}
	if pkg == nil {
		log.Fatalf("no package found in %s", dir)
	}

	// Collect all files for type-checking.
	var files []*ast.File
	for _, file := range pkg.Files {
		files = append(files, file)
	}

	// Type-check the package to get constant values.
	conf := types.Config{Importer: importer.Default()}
	info := &types.Info{
		Defs: make(map[*ast.Ident]types.Object),
	}
	checkedPkg, err := conf.Check(pkg.Name, fset, files, info)
	if err != nil {
		log.Fatalf("type-check error: %v", err)
	}

	dupMap := make(map[int64]string)
	var codes []struct {
		Name  string
		Value int64
	}

	// Iterate over all definitions in the package.
	for ident, obj := range info.Defs {
		if obj == nil {
			continue
		}
		constObj, ok := obj.(*types.Const)
		if !ok {
			continue
		}

		// Ensure that the constant's type is our custom Code type.
		// We check if the type is a named type whose name is "Code".
		named, ok := constObj.Type().(*types.Named)
		if !ok || named.Obj().Name() != "Code" {
			continue
		}

		// Evaluate the constant's value.
		val := constObj.Val()
		if val == nil || val.Kind() != constant.Int {
			log.Fatalf("constant %s does not have an integer value", ident.Name)
		}
		i, ok := constant.Int64Val(val)
		if !ok {
			// Fallback: try to parse as string.
			s := val.ExactString()
			i, err = strconv.ParseInt(s, 10, 64)
			if err != nil {
				log.Fatalf("failed to convert constant %s value (%s) to int64", ident.Name, s)
			}
		}

		// Check for duplicate code values.
		if prev, exists := dupMap[i]; exists {
			log.Fatalf("duplicate code value: %s and %s both have code %d", prev, ident.Name, i)
		}
		dupMap[i] = ident.Name
		codes = append(codes, struct {
			Name  string
			Value int64
		}{Name: ident.Name, Value: i})
	}

	// Generate the file content.
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by generrors; DO NOT EDIT.")
	fmt.Fprintln(&buf, "package errcode")
	fmt.Fprintln(&buf, "")
	fmt.Fprintln(&buf, "// AllCodes is an auto-generated slice containing all error codes.")
	fmt.Fprintln(&buf, "var AllCodes = []Code{")
	for _, code := range codes {
		// Optionally include the numeric value in a comment.
		fmt.Fprintf(&buf, "\t%s, // %d\n", code.Name, code.Value)
	}
	fmt.Fprintln(&buf, "}")

	// Write the generated file into the pkg/errcode directory with a conventional name.
	outputPath := filepath.Join(dir, "generated_errors_slice.go")
	err = os.WriteFile(outputPath, buf.Bytes(), 0644)
	if err != nil {
		log.Fatalf("failed to write file: %v", err)
	}

	// Optionally, print the package path for debugging.
	fmt.Printf("Generated file written to: %s (package %s)\n", outputPath, checkedPkg.Name())
}
