// Code generated by mockery v2.52.3. DO NOT EDIT.

package slack

import (
	context "context"

	alerter "github.com/Sengoku11/go-monorepo/pkg/alerter"

	mock "github.com/stretchr/testify/mock"
)

// MockSend is an autogenerated mock type for the Send type
type MockSend struct {
	mock.Mock
}

type MockSend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSend) EXPECT() *MockSend_Expecter {
	return &MockSend_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, event
func (_m *MockSend) Execute(ctx context.Context, event alerter.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, alerter.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSend_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSend_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - event alerter.Event
func (_e *MockSend_Expecter) Execute(ctx interface{}, event interface{}) *MockSend_Execute_Call {
	return &MockSend_Execute_Call{Call: _e.mock.On("Execute", ctx, event)}
}

func (_c *MockSend_Execute_Call) Run(run func(ctx context.Context, event alerter.Event)) *MockSend_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(alerter.Event))
	})
	return _c
}

func (_c *MockSend_Execute_Call) Return(_a0 error) *MockSend_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSend_Execute_Call) RunAndReturn(run func(context.Context, alerter.Event) error) *MockSend_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSend creates a new instance of MockSend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSend {
	mock := &MockSend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
