// Code generated by mockery v2.52.3. DO NOT EDIT.

package slack

import (
	context "context"

	slack "github.com/slack-go/slack"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// PostMessageContext provides a mock function with given fields: ctx, channelID, options
func (_m *MockClient) PostMessageContext(ctx context.Context, channelID string, options ...slack.MsgOption) (string, string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, channelID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostMessageContext")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...slack.MsgOption) (string, string, error)); ok {
		return rf(ctx, channelID, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...slack.MsgOption) string); ok {
		r0 = rf(ctx, channelID, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...slack.MsgOption) string); ok {
		r1 = rf(ctx, channelID, options...)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, ...slack.MsgOption) error); ok {
		r2 = rf(ctx, channelID, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_PostMessageContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostMessageContext'
type MockClient_PostMessageContext_Call struct {
	*mock.Call
}

// PostMessageContext is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - options ...slack.MsgOption
func (_e *MockClient_Expecter) PostMessageContext(ctx interface{}, channelID interface{}, options ...interface{}) *MockClient_PostMessageContext_Call {
	return &MockClient_PostMessageContext_Call{Call: _e.mock.On("PostMessageContext",
		append([]interface{}{ctx, channelID}, options...)...)}
}

func (_c *MockClient_PostMessageContext_Call) Run(run func(ctx context.Context, channelID string, options ...slack.MsgOption)) *MockClient_PostMessageContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]slack.MsgOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(slack.MsgOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_PostMessageContext_Call) Return(_a0 string, _a1 string, _a2 error) *MockClient_PostMessageContext_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_PostMessageContext_Call) RunAndReturn(run func(context.Context, string, ...slack.MsgOption) (string, string, error)) *MockClient_PostMessageContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
