// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import (
	logger "github.com/Sengoku11/go-monorepo/pkg/logger"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockOptions is an autogenerated mock type for the Options type
type MockOptions struct {
	mock.Mock
}

type MockOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOptions) EXPECT() *MockOptions_Expecter {
	return &MockOptions_Expecter{mock: &_m.Mock}
}

// DisableDebugMode provides a mock function with no fields
func (_m *MockOptions) DisableDebugMode() {
	_m.Called()
}

// MockOptions_DisableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDebugMode'
type MockOptions_DisableDebugMode_Call struct {
	*mock.Call
}

// DisableDebugMode is a helper method to define mock.On call
func (_e *MockOptions_Expecter) DisableDebugMode() *MockOptions_DisableDebugMode_Call {
	return &MockOptions_DisableDebugMode_Call{Call: _e.mock.On("DisableDebugMode")}
}

func (_c *MockOptions_DisableDebugMode_Call) Run(run func()) *MockOptions_DisableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOptions_DisableDebugMode_Call) Return() *MockOptions_DisableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOptions_DisableDebugMode_Call) RunAndReturn(run func()) *MockOptions_DisableDebugMode_Call {
	_c.Run(run)
	return _c
}

// EnableDebugMode provides a mock function with no fields
func (_m *MockOptions) EnableDebugMode() {
	_m.Called()
}

// MockOptions_EnableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDebugMode'
type MockOptions_EnableDebugMode_Call struct {
	*mock.Call
}

// EnableDebugMode is a helper method to define mock.On call
func (_e *MockOptions_Expecter) EnableDebugMode() *MockOptions_EnableDebugMode_Call {
	return &MockOptions_EnableDebugMode_Call{Call: _e.mock.On("EnableDebugMode")}
}

func (_c *MockOptions_EnableDebugMode_Call) Run(run func()) *MockOptions_EnableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOptions_EnableDebugMode_Call) Return() *MockOptions_EnableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOptions_EnableDebugMode_Call) RunAndReturn(run func()) *MockOptions_EnableDebugMode_Call {
	_c.Run(run)
	return _c
}

// WithRateLim provides a mock function with given fields: cooldown, cb
func (_m *MockOptions) WithRateLim(cooldown time.Duration, cb logger.LogMethod) logger.LogMethod {
	ret := _m.Called(cooldown, cb)

	if len(ret) == 0 {
		panic("no return value specified for WithRateLim")
	}

	var r0 logger.LogMethod
	if rf, ok := ret.Get(0).(func(time.Duration, logger.LogMethod) logger.LogMethod); ok {
		r0 = rf(cooldown, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.LogMethod)
		}
	}

	return r0
}

// MockOptions_WithRateLim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithRateLim'
type MockOptions_WithRateLim_Call struct {
	*mock.Call
}

// WithRateLim is a helper method to define mock.On call
//   - cooldown time.Duration
//   - cb logger.LogMethod
func (_e *MockOptions_Expecter) WithRateLim(cooldown interface{}, cb interface{}) *MockOptions_WithRateLim_Call {
	return &MockOptions_WithRateLim_Call{Call: _e.mock.On("WithRateLim", cooldown, cb)}
}

func (_c *MockOptions_WithRateLim_Call) Run(run func(cooldown time.Duration, cb logger.LogMethod)) *MockOptions_WithRateLim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(logger.LogMethod))
	})
	return _c
}

func (_c *MockOptions_WithRateLim_Call) Return(_a0 logger.LogMethod) *MockOptions_WithRateLim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOptions_WithRateLim_Call) RunAndReturn(run func(time.Duration, logger.LogMethod) logger.LogMethod) *MockOptions_WithRateLim_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOptions creates a new instance of MockOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOptions {
	mock := &MockOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
