// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockBasicLogger is an autogenerated mock type for the BasicLogger type
type MockBasicLogger struct {
	mock.Mock
}

type MockBasicLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBasicLogger) EXPECT() *MockBasicLogger_Expecter {
	return &MockBasicLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: message, args
func (_m *MockBasicLogger) Debug(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasicLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockBasicLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasicLogger_Expecter) Debug(message interface{}, args ...interface{}) *MockBasicLogger_Debug_Call {
	return &MockBasicLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasicLogger_Debug_Call) Run(run func(message string, args ...any)) *MockBasicLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasicLogger_Debug_Call) Return() *MockBasicLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_Debug_Call) RunAndReturn(run func(string, ...any)) *MockBasicLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// DisableDebugMode provides a mock function with no fields
func (_m *MockBasicLogger) DisableDebugMode() {
	_m.Called()
}

// MockBasicLogger_DisableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDebugMode'
type MockBasicLogger_DisableDebugMode_Call struct {
	*mock.Call
}

// DisableDebugMode is a helper method to define mock.On call
func (_e *MockBasicLogger_Expecter) DisableDebugMode() *MockBasicLogger_DisableDebugMode_Call {
	return &MockBasicLogger_DisableDebugMode_Call{Call: _e.mock.On("DisableDebugMode")}
}

func (_c *MockBasicLogger_DisableDebugMode_Call) Run(run func()) *MockBasicLogger_DisableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBasicLogger_DisableDebugMode_Call) Return() *MockBasicLogger_DisableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_DisableDebugMode_Call) RunAndReturn(run func()) *MockBasicLogger_DisableDebugMode_Call {
	_c.Run(run)
	return _c
}

// EnableDebugMode provides a mock function with no fields
func (_m *MockBasicLogger) EnableDebugMode() {
	_m.Called()
}

// MockBasicLogger_EnableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDebugMode'
type MockBasicLogger_EnableDebugMode_Call struct {
	*mock.Call
}

// EnableDebugMode is a helper method to define mock.On call
func (_e *MockBasicLogger_Expecter) EnableDebugMode() *MockBasicLogger_EnableDebugMode_Call {
	return &MockBasicLogger_EnableDebugMode_Call{Call: _e.mock.On("EnableDebugMode")}
}

func (_c *MockBasicLogger_EnableDebugMode_Call) Run(run func()) *MockBasicLogger_EnableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBasicLogger_EnableDebugMode_Call) Return() *MockBasicLogger_EnableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_EnableDebugMode_Call) RunAndReturn(run func()) *MockBasicLogger_EnableDebugMode_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message, args
func (_m *MockBasicLogger) Error(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasicLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockBasicLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasicLogger_Expecter) Error(message interface{}, args ...interface{}) *MockBasicLogger_Error_Call {
	return &MockBasicLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasicLogger_Error_Call) Run(run func(message string, args ...any)) *MockBasicLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasicLogger_Error_Call) Return() *MockBasicLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_Error_Call) RunAndReturn(run func(string, ...any)) *MockBasicLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: message, args
func (_m *MockBasicLogger) Fatal(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasicLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockBasicLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasicLogger_Expecter) Fatal(message interface{}, args ...interface{}) *MockBasicLogger_Fatal_Call {
	return &MockBasicLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasicLogger_Fatal_Call) Run(run func(message string, args ...any)) *MockBasicLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasicLogger_Fatal_Call) Return() *MockBasicLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_Fatal_Call) RunAndReturn(run func(string, ...any)) *MockBasicLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: message, args
func (_m *MockBasicLogger) Info(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasicLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockBasicLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasicLogger_Expecter) Info(message interface{}, args ...interface{}) *MockBasicLogger_Info_Call {
	return &MockBasicLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasicLogger_Info_Call) Run(run func(message string, args ...any)) *MockBasicLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasicLogger_Info_Call) Return() *MockBasicLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_Info_Call) RunAndReturn(run func(string, ...any)) *MockBasicLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function with given fields: message, args
func (_m *MockBasicLogger) Panic(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasicLogger_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockBasicLogger_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasicLogger_Expecter) Panic(message interface{}, args ...interface{}) *MockBasicLogger_Panic_Call {
	return &MockBasicLogger_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasicLogger_Panic_Call) Run(run func(message string, args ...any)) *MockBasicLogger_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasicLogger_Panic_Call) Return() *MockBasicLogger_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_Panic_Call) RunAndReturn(run func(string, ...any)) *MockBasicLogger_Panic_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: message, args
func (_m *MockBasicLogger) Warn(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasicLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockBasicLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasicLogger_Expecter) Warn(message interface{}, args ...interface{}) *MockBasicLogger_Warn_Call {
	return &MockBasicLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasicLogger_Warn_Call) Run(run func(message string, args ...any)) *MockBasicLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasicLogger_Warn_Call) Return() *MockBasicLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasicLogger_Warn_Call) RunAndReturn(run func(string, ...any)) *MockBasicLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// NewMockBasicLogger creates a new instance of MockBasicLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBasicLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBasicLogger {
	mock := &MockBasicLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
