// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import (
	context "context"

	alerter "github.com/Sengoku11/go-monorepo/pkg/alerter"

	mock "github.com/stretchr/testify/mock"
)

// MockAlerter is an autogenerated mock type for the Alerter type
type MockAlerter struct {
	mock.Mock
}

type MockAlerter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlerter) EXPECT() *MockAlerter_Expecter {
	return &MockAlerter_Expecter{mock: &_m.Mock}
}

// AddHook provides a mock function with given fields: hook
func (_m *MockAlerter) AddHook(hook alerter.Alerter) {
	_m.Called(hook)
}

// MockAlerter_AddHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHook'
type MockAlerter_AddHook_Call struct {
	*mock.Call
}

// AddHook is a helper method to define mock.On call
//   - hook alerter.Alerter
func (_e *MockAlerter_Expecter) AddHook(hook interface{}) *MockAlerter_AddHook_Call {
	return &MockAlerter_AddHook_Call{Call: _e.mock.On("AddHook", hook)}
}

func (_c *MockAlerter_AddHook_Call) Run(run func(hook alerter.Alerter)) *MockAlerter_AddHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(alerter.Alerter))
	})
	return _c
}

func (_c *MockAlerter_AddHook_Call) Return() *MockAlerter_AddHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAlerter_AddHook_Call) RunAndReturn(run func(alerter.Alerter)) *MockAlerter_AddHook_Call {
	_c.Run(run)
	return _c
}

// Alert provides a mock function with given fields: ctx, channel, message, payload
func (_m *MockAlerter) Alert(ctx context.Context, channel alerter.Channel, message string, payload map[string]any) {
	_m.Called(ctx, channel, message, payload)
}

// MockAlerter_Alert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alert'
type MockAlerter_Alert_Call struct {
	*mock.Call
}

// Alert is a helper method to define mock.On call
//   - ctx context.Context
//   - channel alerter.Channel
//   - message string
//   - payload map[string]any
func (_e *MockAlerter_Expecter) Alert(ctx interface{}, channel interface{}, message interface{}, payload interface{}) *MockAlerter_Alert_Call {
	return &MockAlerter_Alert_Call{Call: _e.mock.On("Alert", ctx, channel, message, payload)}
}

func (_c *MockAlerter_Alert_Call) Run(run func(ctx context.Context, channel alerter.Channel, message string, payload map[string]any)) *MockAlerter_Alert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(alerter.Channel), args[2].(string), args[3].(map[string]any))
	})
	return _c
}

func (_c *MockAlerter_Alert_Call) Return() *MockAlerter_Alert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAlerter_Alert_Call) RunAndReturn(run func(context.Context, alerter.Channel, string, map[string]any)) *MockAlerter_Alert_Call {
	_c.Run(run)
	return _c
}

// NewMockAlerter creates a new instance of MockAlerter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlerter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlerter {
	mock := &MockAlerter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
