// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockControls is an autogenerated mock type for the Controls type
type MockControls struct {
	mock.Mock
}

type MockControls_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControls) EXPECT() *MockControls_Expecter {
	return &MockControls_Expecter{mock: &_m.Mock}
}

// DisableDebugMode provides a mock function with no fields
func (_m *MockControls) DisableDebugMode() {
	_m.Called()
}

// MockControls_DisableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDebugMode'
type MockControls_DisableDebugMode_Call struct {
	*mock.Call
}

// DisableDebugMode is a helper method to define mock.On call
func (_e *MockControls_Expecter) DisableDebugMode() *MockControls_DisableDebugMode_Call {
	return &MockControls_DisableDebugMode_Call{Call: _e.mock.On("DisableDebugMode")}
}

func (_c *MockControls_DisableDebugMode_Call) Run(run func()) *MockControls_DisableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControls_DisableDebugMode_Call) Return() *MockControls_DisableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControls_DisableDebugMode_Call) RunAndReturn(run func()) *MockControls_DisableDebugMode_Call {
	_c.Run(run)
	return _c
}

// EnableDebugMode provides a mock function with no fields
func (_m *MockControls) EnableDebugMode() {
	_m.Called()
}

// MockControls_EnableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDebugMode'
type MockControls_EnableDebugMode_Call struct {
	*mock.Call
}

// EnableDebugMode is a helper method to define mock.On call
func (_e *MockControls_Expecter) EnableDebugMode() *MockControls_EnableDebugMode_Call {
	return &MockControls_EnableDebugMode_Call{Call: _e.mock.On("EnableDebugMode")}
}

func (_c *MockControls_EnableDebugMode_Call) Run(run func()) *MockControls_EnableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControls_EnableDebugMode_Call) Return() *MockControls_EnableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControls_EnableDebugMode_Call) RunAndReturn(run func()) *MockControls_EnableDebugMode_Call {
	_c.Run(run)
	return _c
}

// NewMockControls creates a new instance of MockControls. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControls(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControls {
	mock := &MockControls{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
