// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockAdvanced is an autogenerated mock type for the Advanced type
type MockAdvanced struct {
	mock.Mock
}

type MockAdvanced_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdvanced) EXPECT() *MockAdvanced_Expecter {
	return &MockAdvanced_Expecter{mock: &_m.Mock}
}

// Fatal provides a mock function with given fields: message, args
func (_m *MockAdvanced) Fatal(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockAdvanced_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockAdvanced_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockAdvanced_Expecter) Fatal(message interface{}, args ...interface{}) *MockAdvanced_Fatal_Call {
	return &MockAdvanced_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockAdvanced_Fatal_Call) Run(run func(message string, args ...any)) *MockAdvanced_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAdvanced_Fatal_Call) Return() *MockAdvanced_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdvanced_Fatal_Call) RunAndReturn(run func(string, ...any)) *MockAdvanced_Fatal_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function with given fields: message, args
func (_m *MockAdvanced) Panic(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockAdvanced_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockAdvanced_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockAdvanced_Expecter) Panic(message interface{}, args ...interface{}) *MockAdvanced_Panic_Call {
	return &MockAdvanced_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockAdvanced_Panic_Call) Run(run func(message string, args ...any)) *MockAdvanced_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAdvanced_Panic_Call) Return() *MockAdvanced_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAdvanced_Panic_Call) RunAndReturn(run func(string, ...any)) *MockAdvanced_Panic_Call {
	_c.Run(run)
	return _c
}

// NewMockAdvanced creates a new instance of MockAdvanced. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdvanced(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdvanced {
	mock := &MockAdvanced{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
