// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockBasic is an autogenerated mock type for the Basic type
type MockBasic struct {
	mock.Mock
}

type MockBasic_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBasic) EXPECT() *MockBasic_Expecter {
	return &MockBasic_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: message, args
func (_m *MockBasic) Debug(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasic_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockBasic_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasic_Expecter) Debug(message interface{}, args ...interface{}) *MockBasic_Debug_Call {
	return &MockBasic_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasic_Debug_Call) Run(run func(message string, args ...any)) *MockBasic_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasic_Debug_Call) Return() *MockBasic_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasic_Debug_Call) RunAndReturn(run func(string, ...any)) *MockBasic_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message, args
func (_m *MockBasic) Error(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasic_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockBasic_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasic_Expecter) Error(message interface{}, args ...interface{}) *MockBasic_Error_Call {
	return &MockBasic_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasic_Error_Call) Run(run func(message string, args ...any)) *MockBasic_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasic_Error_Call) Return() *MockBasic_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasic_Error_Call) RunAndReturn(run func(string, ...any)) *MockBasic_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: message, args
func (_m *MockBasic) Info(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasic_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockBasic_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasic_Expecter) Info(message interface{}, args ...interface{}) *MockBasic_Info_Call {
	return &MockBasic_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasic_Info_Call) Run(run func(message string, args ...any)) *MockBasic_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasic_Info_Call) Return() *MockBasic_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasic_Info_Call) RunAndReturn(run func(string, ...any)) *MockBasic_Info_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: message, args
func (_m *MockBasic) Warn(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockBasic_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockBasic_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockBasic_Expecter) Warn(message interface{}, args ...interface{}) *MockBasic_Warn_Call {
	return &MockBasic_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockBasic_Warn_Call) Run(run func(message string, args ...any)) *MockBasic_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockBasic_Warn_Call) Return() *MockBasic_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBasic_Warn_Call) RunAndReturn(run func(string, ...any)) *MockBasic_Warn_Call {
	_c.Run(run)
	return _c
}

// NewMockBasic creates a new instance of MockBasic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBasic(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBasic {
	mock := &MockBasic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
