// Code generated by mockery v2.52.3. DO NOT EDIT.

package logger

import (
	context "context"

	alerter "github.com/Sengoku11/go-monorepo/pkg/alerter"

	logger "github.com/Sengoku11/go-monorepo/pkg/logger"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// AddHook provides a mock function with given fields: hook
func (_m *MockLogger) AddHook(hook alerter.Alerter) {
	_m.Called(hook)
}

// MockLogger_AddHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHook'
type MockLogger_AddHook_Call struct {
	*mock.Call
}

// AddHook is a helper method to define mock.On call
//   - hook alerter.Alerter
func (_e *MockLogger_Expecter) AddHook(hook interface{}) *MockLogger_AddHook_Call {
	return &MockLogger_AddHook_Call{Call: _e.mock.On("AddHook", hook)}
}

func (_c *MockLogger_AddHook_Call) Run(run func(hook alerter.Alerter)) *MockLogger_AddHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(alerter.Alerter))
	})
	return _c
}

func (_c *MockLogger_AddHook_Call) Return() *MockLogger_AddHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_AddHook_Call) RunAndReturn(run func(alerter.Alerter)) *MockLogger_AddHook_Call {
	_c.Run(run)
	return _c
}

// Alert provides a mock function with given fields: ctx, message, options, payload
func (_m *MockLogger) Alert(ctx context.Context, message string, options alerter.Options, payload map[string]any) {
	_m.Called(ctx, message, options, payload)
}

// MockLogger_Alert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alert'
type MockLogger_Alert_Call struct {
	*mock.Call
}

// Alert is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - options alerter.Options
//   - payload map[string]any
func (_e *MockLogger_Expecter) Alert(ctx interface{}, message interface{}, options interface{}, payload interface{}) *MockLogger_Alert_Call {
	return &MockLogger_Alert_Call{Call: _e.mock.On("Alert", ctx, message, options, payload)}
}

func (_c *MockLogger_Alert_Call) Run(run func(ctx context.Context, message string, options alerter.Options, payload map[string]any)) *MockLogger_Alert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(alerter.Options), args[3].(map[string]any))
	})
	return _c
}

func (_c *MockLogger_Alert_Call) Return() *MockLogger_Alert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Alert_Call) RunAndReturn(run func(context.Context, string, alerter.Options, map[string]any)) *MockLogger_Alert_Call {
	_c.Run(run)
	return _c
}

// Debug provides a mock function with given fields: message, args
func (_m *MockLogger) Debug(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockLogger_Expecter) Debug(message interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(message string, args ...any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(string, ...any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// DisableDebugMode provides a mock function with no fields
func (_m *MockLogger) DisableDebugMode() {
	_m.Called()
}

// MockLogger_DisableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDebugMode'
type MockLogger_DisableDebugMode_Call struct {
	*mock.Call
}

// DisableDebugMode is a helper method to define mock.On call
func (_e *MockLogger_Expecter) DisableDebugMode() *MockLogger_DisableDebugMode_Call {
	return &MockLogger_DisableDebugMode_Call{Call: _e.mock.On("DisableDebugMode")}
}

func (_c *MockLogger_DisableDebugMode_Call) Run(run func()) *MockLogger_DisableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_DisableDebugMode_Call) Return() *MockLogger_DisableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_DisableDebugMode_Call) RunAndReturn(run func()) *MockLogger_DisableDebugMode_Call {
	_c.Run(run)
	return _c
}

// EnableDebugMode provides a mock function with no fields
func (_m *MockLogger) EnableDebugMode() {
	_m.Called()
}

// MockLogger_EnableDebugMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDebugMode'
type MockLogger_EnableDebugMode_Call struct {
	*mock.Call
}

// EnableDebugMode is a helper method to define mock.On call
func (_e *MockLogger_Expecter) EnableDebugMode() *MockLogger_EnableDebugMode_Call {
	return &MockLogger_EnableDebugMode_Call{Call: _e.mock.On("EnableDebugMode")}
}

func (_c *MockLogger_EnableDebugMode_Call) Run(run func()) *MockLogger_EnableDebugMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_EnableDebugMode_Call) Return() *MockLogger_EnableDebugMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_EnableDebugMode_Call) RunAndReturn(run func()) *MockLogger_EnableDebugMode_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message, args
func (_m *MockLogger) Error(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockLogger_Expecter) Error(message interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(message string, args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(string, ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: message, args
func (_m *MockLogger) Fatal(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockLogger_Expecter) Fatal(message interface{}, args ...interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(message string, args ...any)) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(string, ...any)) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: message, args
func (_m *MockLogger) Info(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockLogger_Expecter) Info(message interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(message string, args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(string, ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function with given fields: message, args
func (_m *MockLogger) Panic(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockLogger_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockLogger_Expecter) Panic(message interface{}, args ...interface{}) *MockLogger_Panic_Call {
	return &MockLogger_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Panic_Call) Run(run func(message string, args ...any)) *MockLogger_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Panic_Call) Return() *MockLogger_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Panic_Call) RunAndReturn(run func(string, ...any)) *MockLogger_Panic_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: message, args
func (_m *MockLogger) Warn(message string, args ...any) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - message string
//   - args ...any
func (_e *MockLogger_Expecter) Warn(message interface{}, args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{message}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(message string, args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(string, ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// WithRateLim provides a mock function with given fields: cooldown, cb
func (_m *MockLogger) WithRateLim(cooldown time.Duration, cb logger.LogMethod) logger.LogMethod {
	ret := _m.Called(cooldown, cb)

	if len(ret) == 0 {
		panic("no return value specified for WithRateLim")
	}

	var r0 logger.LogMethod
	if rf, ok := ret.Get(0).(func(time.Duration, logger.LogMethod) logger.LogMethod); ok {
		r0 = rf(cooldown, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.LogMethod)
		}
	}

	return r0
}

// MockLogger_WithRateLim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithRateLim'
type MockLogger_WithRateLim_Call struct {
	*mock.Call
}

// WithRateLim is a helper method to define mock.On call
//   - cooldown time.Duration
//   - cb logger.LogMethod
func (_e *MockLogger_Expecter) WithRateLim(cooldown interface{}, cb interface{}) *MockLogger_WithRateLim_Call {
	return &MockLogger_WithRateLim_Call{Call: _e.mock.On("WithRateLim", cooldown, cb)}
}

func (_c *MockLogger_WithRateLim_Call) Run(run func(cooldown time.Duration, cb logger.LogMethod)) *MockLogger_WithRateLim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(logger.LogMethod))
	})
	return _c
}

func (_c *MockLogger_WithRateLim_Call) Return(_a0 logger.LogMethod) *MockLogger_WithRateLim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogger_WithRateLim_Call) RunAndReturn(run func(time.Duration, logger.LogMethod) logger.LogMethod) *MockLogger_WithRateLim_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
